#!/usr/bin/perl

use strict;
use warnings;

use Template;
use Literature::Schema;

my $tt = Template->new({
  INCLUDE_PATH => [ qw( in tt_lib ) ],
  OUTPUT_PATH  => 'docs',
  WRAPPER      => 'main.tt',
});

my $sch = Literature::Schema->get_schema;

# Note index2 for testing
$tt->process('index.tt', {}, 'index2.html')
  or die $tt->error;
