#!/usr/bin/perl

use strict;
use warnings;

use FindBin '$Bin';
use DBIx::Class::Schema::Loader qw/ make_schema_at /;

make_schema_at(
  'Literature::Schema', {
    dump_directory => "$Bin/../lib",
    components     => [ 'InflateColumn::DateTime' ],
    use_moose      => 1,
  },
  [ 'dbi:mysql:literature','literature','l173r47ur3' ],
);
